[tool.poetry]
name = "my-gtp-bot"
version = "0.1.0"
description = ""
authors = ["aldi <alkin.denis@gmail.com>"]
readme = "README.md"
packages = [{include = "my-gtp-bot"}]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.21.0"
SQLAlchemy = "^2.0.4"
alembic = "^1.8.1"
aiogram = {version = "^3.0.0b7", allow-prereleases = true}
openai = "^0.27.8"
aiosqlite = "^0.19.0"
pydantic-settings = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
