"""fix: исправил колонки с Enum

Revision ID: 820c2e7a5496
Revises: 0f7e2311b6a6
Create Date: 2023-11-21 10:09:26.342272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820c2e7a5496'
down_revision: Union[str, None] = '0f7e2311b6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
